name: Python application

on:
    push:
        branches: [ main_sample, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: code checkout 
          uses: actions/checkout@v4
        
        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
              python-version: '3.10'

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: Set environment variable
          run: echo "BOT_TOKEN=${{secrets.BOT_TOKEN}}">> .env

        - name: Run telegram_bot.py
          run: |
              python telegram_bot.py